### ISSUE TITLE
Import Module Error

### ISSUE THREAD

**Issue by Kevin95580** [acidb/mobiscroll-demos-react-ts#1]
Greetings of the day,

The code very well arranged and also it is very userful but when i try to  install  '@mobiscroll/react' module it generates errror.
After that I found as issue there is no error but module '@mobiscroll/react' is changed to '@mobiscroll/react-lite'.So, it is generating the error. After that i have imported '@mobiscroll/react-lite' library but now imported modules are not found or not matches the name so I unnable to use this Calender code . Please give me appropriate solutoin of it

**Comment by dioslaska** [comment]
Hi Kevin, Mobiscroll is a commercial product, and the package can be installed from a private npm registry.
You can find the steps [here](https://github.com/acidb/mobiscroll-demos-react-ts?tab=readme-ov-file#required-steps-to-run-the-project-locally) on how to install the trial version of the package.
For licensing option please visit our [pricing page](https://mobiscroll.com/pricing).
