### ISSUE TITLE
Can not set `eventDisplay` prop

### ISSUE THREAD

**Issue by leoalipazaga** [acidb/mobiscroll-demos-react-ts#2]
## Description

Can not set `eventDisplay` prop. Probably is a version error. Could help me please?

## Version
```
"@mobiscroll/react": "5.28.0"
```
## Screenshot/Evidences
<img width="997" alt="image" src="https://github.com/user-attachments/assets/13f89ecb-6a89-481a-b1b1-7b27cc92dad2">

**Comment by dioslaska** [comment]
That's right, Mobiscroll v5.32.0 is needed to use the `eventDisplay` property.
